services:
  postgres:
    image: postgres:16
    container_name: postgres_t2sql_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - ./dvdrental.tar:/tmp/dvdrental.tar

volumes:
  postgres_data: